In [10]:
pip install pandas

In [2]:
!pip install pandas

In [11]:
import pandas as pd
import numpy as np

In [12]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
data = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','columen2','column3','column4'])

In [15]:
data

column1  columen2  column3  column4
row1        0         1        2        3
row2        4         5        6        7
row3        8         9       10       11
row4       12        13       14       15
row5       16        17       18       19

In [16]:
# csv means data is presented in comma seprated foramt
data.to_csv('test1.csv')

In [18]:
data.loc['row1']

column1     0
columen2    1
column3     2
column4     3
Name: row1, dtype: int32

In [20]:
type(data.loc['row1'])

pandas.core.series.Series

In [19]:
# retrieve all rows and columns
data.iloc[:,:]

column1  columen2  column3  column4
row1        0         1        2        3
row2        4         5        6        7
row3        8         9       10       11
row4       12        13       14       15
row5       16        17       18       19

In [21]:
data.iloc[1:,:]

column1  columen2  column3  column4
row2        4         5        6        7
row3        8         9       10       11
row4       12        13       14       15
row5       16        17       18       19

In [22]:
data.iloc[:,3:]

column4
row1        3
row2        7
row3       11
row4       15
row5       19

In [27]:
# if you need 3 rows and 2columns

data.iloc[0:3,0:2]

column1  columen2
row1        0         1
row2        4         5
row3        8         9

In [23]:
data1 = data.iloc[:,:].values

In [24]:
data1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
type(data1)

numpy.ndarray

In [34]:
data.isnull().sum()

column1     0
columen2    0
column3     0
column4     0
dtype: int64

In [29]:
data['column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: column1, dtype: int64

In [30]:
data1[0][0]

0

In [31]:
data1[1][0]

4

In [ ]:
data

In [33]:
num = len(data1)
for i in range(num):
    print(data1[i][0])

0
4
8
12
16


In [35]:
num = len(data1)
for i in range(num):
    print(data1[i][1])

1
5
9
13
17


In [36]:
data1[0][3]

3

In [37]:
data1[2][1]

9

In [ ]:
x = [1, 4, 6, 5, 1.5, 2.5, 3.5, ]
n = len(8)


# funciton = weights
